**Convert eGrid Zipcode Excel Data into Usable Format**

In [1]:
#import libraries
import pandas as pd
import numpy as np
import json

#read Excel into Pandas dataframe 
excel_file_path = '/Users/arjunchadha/Desktop/zip_to_egrid/power_profiler_historical_zip_codes.xlsx'

# Provide a dictionary with column names as keys and data types as values
# Set the 'zipcode' column data type as a string to preserve leading zeros
dtype_dict = {'ZIP (character)': str}

# Read the Excel sheet into a DataFrame with specified data types
df = pd.read_excel(excel_file_path, dtype=dtype_dict)

#save dataframe as csv
#csv_file_path = 'output_file.csv'
#df.to_csv(csv_file_path, index=False)

In [2]:
df.head(5)

,ZIP (character),ZIP (numeric),State,eGRID Subregion #1,eGRID Subregion #2,eGRID Subregion #3,Alphabetical Sort 1,Alphabetical Sort 2,Alphabetical Sort 3,Concatenated,Notes
0,00001,1,AK,AKMS,NaN,NaN,NaN,NaN,AKMS,AKMS,NaN
1,00002,2,AK,AKMS,NaN,NaN,NaN,NaN,AKMS,AKMS,NaN
2,00003,3,AK,AKMS,NaN,NaN,NaN,NaN,AKMS,AKMS,NaN
3,00004,4,AK,AKMS,NaN,NaN,NaN,NaN,AKMS,AKMS,NaN
4,00005,5,AK,AKMS,NaN,NaN,NaN,NaN,AKMS,AKMS,NaN

In [3]:
df = df[['ZIP (character)','eGRID Subregion #1']]
df.head(5)

  ZIP (character) eGRID Subregion #1
0           00001               AKMS
1           00002               AKMS
2           00003               AKMS
3           00004               AKMS
4           00005               AKMS

In [4]:
df.rename(columns = {'ZIP (character)':'zipcode', 'eGRID Subregion #1':'eGRID_subregion'}, inplace = True)
df.head(5)

  zipcode eGRID_subregion
0   00001            AKMS
1   00002            AKMS
2   00003            AKMS
3   00004            AKMS
4   00005            AKMS

In [5]:
# Convert the DataFrame to a dictionary with zip codes as keys and eGRID subregions as values
zip_egrid_dict = dict(zip(df['zipcode'], df['eGRID_subregion']))

# Save the dictionary to a JSON file
with open('data.json', 'w') as json_file:
    json.dump(zip_egrid_dict, json_file, indent=2)